language: python

python:
  - "2.7"

env:
  - TOXENV=py27-17


branches:
    only:
        - master

install: pip install --quiet tox

# command to run tests
script: tox

after_script:
    - if [ $TOXENV == "py27-17" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
