language: python

python:
  - "2.7"

env:
  - TOXENV=py26-14
  - TOXENV=py26-15
  - TOXENV=py26-16
  - TOXENV=py32-15
  - TOXENV=py32-16
  - TOXENV=py32-17
  - TOXENV=py33-15
  - TOXENV=py33-16
  - TOXENV=py33-17
  - TOXENV=py34-17
  - TOXENV=py27-14
  - TOXENV=py27-15
  - TOXENV=py27-16
  - TOXENV=py27-17


branches:
    only:
        - master

install: pip install --quiet --use-mirrors tox

# command to run tests
script: tox

after_script:
    - if [ $TOXENV == "py27-17" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
